/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author avineet75
 */
public class tictactoe extends javax.swing.JFrame {

    /**
     * Creates new form tictactoe
     */
    public tictactoe() {
        initComponents();
    }
String c,s;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        l5 = new javax.swing.JLabel();
        jb1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        jb2 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });

        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });

        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });

        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter name of player 1");

        jLabel4.setText("Enter name of player 2");

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });

        jb1.setText("input");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });

        jLabel5.setText("enter no of gmes");

        jb2.setText("submit");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });

        jb3.setText("Reset");
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(t4)
                    .addComponent(t7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(t6)
                        .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(48, 48, 48)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jb2)
                                                    .addGap(43, 43, 43)
                                                    .addComponent(jb3))))))
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf2)
                                    .addComponent(tf3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb1)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb1))
                .addGap(18, 18, 18)
                .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)))
                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb2)
                    .addComponent(jb3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here
        
    }//GEN-LAST:event_t4ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_t2ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_t9ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_t6ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_t3ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_t5ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here: 
      
    }//GEN-LAST:event_t7ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_t8ActionPerformed
    
    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tf1ActionPerformed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        // TODO add your handling code here:
        c=tf1.getText();
        s=tf2.getText();
        int n=Integer.parseInt(tf3.getText());
        l5.setText(" "+c+ " and " +s +" are playing " +n+ " number of games ");
        
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        // 
        //TODO add your handling code here:
        int i;
        for(i=1;i<=9;i++)
        {
        if(t1.getText()!=null)
        {
            if(t2.getText()!=null&&t3.getText()!=null)
        {
            if(t1.getText().equals(t2.getText())&&t1.getText().equals(t3.getText()))
            {
                if(t1.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t1.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        if(t4.getText()!=null&&t7.getText()!=null)
        {
            if(t1.getText().equals(t4.getText())&&t1.getText().equals(t7.getText()))
            {
                if(t1.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t1.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        if(t5.getText()!=null&&t9.getText()!=null)
        {
            if(t1.getText().equals(t5.getText())&&t1.getText().equals(t9.getText()))
            {
                if(t1.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t1.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
       
        continue;
    }   
        if(t2.getText()!=null)
        {
        if(t1.getText()!=null&&t3.getText()!=null)
        {
            if(t2.getText().equals(t1.getText())&&t2.getText().equals(t3.getText()))
            {
                if(t2.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t2.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        if(t5.getText()!=null&&t8.getText()!=null)
        {
            if(t2.getText().equals(t5.getText())&&t2.getText().equals(t8.getText()))
            {
                if(t2.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t2.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
       continue;
        }
        if(t3.getText()!=null)
        {
    if(t2.getText()!=null&&t1.getText()!=null)
        {
            if(t3.getText().equals(t2.getText())&&t3.getText().equals(t1.getText()))
            {
                if(t3.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t3.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        if(t6.getText()!=null&&t9.getText()!=null)
        {
            if(t3.getText().equals(t6.getText())&&t3.getText().equals(t9.getText()))
            {
                if(t3.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t3.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        if(t5.getText()!=null&&t7.getText()!=null)
        {
            if(t3.getText().equals(t5.getText())&&t3.getText().equals(t7.getText()))
            {
                if(t3.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t3.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        continue;
        }
if(t4.getText()!=null)
{
if(t1.getText()!=null&&t7.getText()!=null)
        {
            if(t1.getText().equals(t4.getText())&&t4.getText().equals(t7.getText()))
            {
                if(t4.getText().equals("x"))
                    l1.setText(" "+tf1.getText());
                else if(t4.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        if(t5.getText()!=null&&t6.getText()!=null)
        {
            if(t4.getText().equals(t5.getText())&&t4.getText().equals(t6.getText()))
            {
                if(t4.getText().equals("x"))
                    l1.setText(" "+tf1.getText());
                else if(t4.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        continue;
} 
if(t5.getText()!=null)
{
     if(t2.getText()!=null&&t8.getText()!=null)
        {
            if(t5.getText().equals(t2.getText())&&t5.getText().equals(t8.getText()))
            {
                if(t5.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t5.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        if(t4.getText()!=null&&t6.getText()!=null)
        {
            if(t5.getText().equals(t4.getText())&&t5.getText().equals(t6.getText()))
            {
                if(t5.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t5.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        if(t1.getText()!=null&&t9.getText()!=null)
        {
            if(t1.getText().equals(t5.getText())&&t5.getText().equals(t9.getText()))
            {
                if(t5.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
               else if(t5.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        if(t3.getText()!=null&&t7.getText()!=null)
        {
            if(t5.getText().equals(t3.getText())&&t5.getText().equals(t7.getText()))
            {
                if(t5.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t5.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        continue;
}
if(t6.getText()!=null)
{
    if(t3.getText()!=null&&t9.getText()!=null)
        {
            if(t3.getText().equals(t6.getText())&&t3.getText().equals(t9.getText()))
            {
                if(t3.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t3.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        if(t4.getText()!=null&&t5.getText()!=null)
        {
            if(t6.getText().equals(t4.getText())&&t4.getText().equals(t5.getText()))
            {
                if(t6.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
               else if(t6.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        continue;
}
        if(t7.getText()!=null)
        {
              if(t1.getText()!=null&&t4.getText()!=null)
        {
            if(t7.getText().equals(t1.getText())&&t7.getText().equals(t4.getText()))
            {
                if(t1.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t1.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        if(t8.getText()!=null&&t9.getText()!=null)
        {
            if(t7.getText().equals(t8.getText())&&t7.getText().equals(t9.getText()))
            {
                if(t7.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
               else if(t7.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        if(t5.getText()!=null&&t3.getText()!=null)
        {
            if(t7.getText().equals(t5.getText())&&t7.getText().equals(t3.getText()))
            {
                if(t7.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t7.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        continue;
        }
        if(t8.getText()!=null)
        {
            if(t2.getText()!=null&&t5.getText()!=null)
        {
            if(t8.getText().equals(t2.getText())&&t8.getText().equals(t5.getText()))
            {
                if(t8.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t8.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        if(t7.getText()!=null&&t9.getText()!=null)
        {
            if(t8.getText().equals(t7.getText())&&t8.getText().equals(t9.getText()))
            {
                if(t8.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t8.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        continue;
        }
        if(t9.getText()!=null)
        {
              if(t7.getText()!=null&&t8.getText()!=null)
        {
            if(t9.getText().equals(t7.getText())&&t9.getText().equals(t8.getText()))
            {
                if(t9.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t9.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        if(t3.getText()!=null&&t6.getText()!=null)
        {
            if(t3.getText().equals(t9.getText())&&t9.getText().equals(t6.getText()))
            {
                if(t3.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
               else if(t3.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
                break;
            }
        }
        if(t1.getText()!=null&&t5.getText()!=null)
        {
            if(t1.getText().equals(t9.getText())&&t9.getText().equals(t5.getText()))
            {
                if(t1.getText().equals("x"))
                    l3.setText(" "+tf1.getText());
                else if(t1.getText().equals("o"))
                    l3.setText(" " +tf2.getText());
                else
                    l3.setText(" No one Wins");
               break;
            }
        }
        
        continue;
        }
        }
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        // TODO add your handling code here:
        tf1.setText(null);
        tf2.setText(null);
        tf3.setText(null);
        t1.setText(null);
        t2.setText(null);
        t3.setText(null);
        t4.setText(null);
        t5.setText(null);
        t6.setText(null);
        t7.setText(null);
        t8.setText(null);
        t9.setText(null);
        l5.setText(null);
        l3.setText(null);
    }//GEN-LAST:event_jb3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tictactoe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    // End of variables declaration//GEN-END:variables
}
